server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/milktea_shop?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: 8b1c4d6f90c2481ca6cb5dbf9d7c24b78f2b2f6b17fb4df9987043b3f34c7e2d
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
